/*
TITLE: Negotiation Detailed Report
PURPOSE: Comprehensive negotiation details with requisition, line-level, and pricing information
AUTHOR: AI Agent
PARAMETERS: P_REQ_BU_NAME, P_NEGOTIATION_NUMBER, P_OPEN_DATE_FROM, P_OPEN_DATE_TO
*/

WITH
-- 1. Parameters CTE
PARAMS AS (
    SELECT /*+ qb_name(PARAMS) */
           :P_REQ_BU_NAME AS REQ_BU_NAME
          ,:P_NEGOTIATION_NUMBER AS NEGOTIATION_NUMBER
          ,TRUNC(:P_OPEN_DATE_FROM) AS OPEN_DATE_FROM
          ,TRUNC(:P_OPEN_DATE_TO) AS OPEN_DATE_TO
    FROM   DUAL
),

-- 2. Negotiation Header Master
NEGOTIATION_HEADER_MASTER AS (
    SELECT /*+ qb_name(NEG_HDR) MATERIALIZE PARALLEL(2) */
           PAH.AUCTION_HEADER_ID
          ,PAH.DOCUMENT_NUMBER AS NEGOTIATION_NUMBER
          ,PAH.AUCTION_TITLE AS NEGOTIATION_TITLE
          ,PAH.AUCTION_STATUS AS NEGOTIATION_STATUS
          ,PAH.OPEN_BIDDING_DATE AS NEGOTIATION_OPEN_DATE
          ,PAH.CLOSE_BIDDING_DATE AS NEGOTIATION_CLOSED_DATE
    FROM   PON_AUCTION_HEADERS_ALL PAH
          ,PARAMS P
    WHERE  1=1
      AND  (P.NEGOTIATION_NUMBER IS NULL OR PAH.DOCUMENT_NUMBER = P.NEGOTIATION_NUMBER)
      AND  (P.OPEN_DATE_FROM IS NULL OR TRUNC(PAH.OPEN_BIDDING_DATE) >= P.OPEN_DATE_FROM)
      AND  (P.OPEN_DATE_TO IS NULL OR TRUNC(PAH.OPEN_BIDDING_DATE) <= P.OPEN_DATE_TO)
),

-- 3. Negotiation Line Master
NEGOTIATION_LINE_MASTER AS (
    SELECT /*+ qb_name(NEG_LINE) MATERIALIZE */
           PAIP.AUCTION_HEADER_ID
          ,PAIP.LINE_NUMBER AS NEGOTIATION_LINE_NUMBER
          ,PAIP.ITEM_DESCRIPTION AS NEGOTIATION_LINE_DESCRIPTION
          ,PAIP.ORDER_TYPE_LOOKUP_CODE AS LINE_TYPE
          ,PAIP.CATEGORY_ID
          ,PAIP.REQUESTED_DELIVERY_DATE
          ,PAIP.CURRENT_PRICE
          ,PAIP.REQUISITION_NUMBER AS PR_NUMBER
    FROM   PON_AUCTION_ITEM_PRICES_ALL PAIP
),

-- 4. Category Master
CATEGORY_MASTER AS (
    SELECT /*+ qb_name(CAT_MST) MATERIALIZE */
           ECV.CATEGORY_ID
          ,ECV.CATEGORY_NAME
    FROM   EGP_CATEGORIES_VL ECV
),

-- 5. Business Unit Master
BU_MASTER AS (
    SELECT /*+ qb_name(BU_MST) MATERIALIZE */
           HAOU.ORGANIZATION_ID
          ,HAOU.NAME AS BU_NAME
    FROM   HR_ALL_ORGANIZATION_UNITS HAOU
),

-- 6. Final Detailed Report
NEGOTIATION_DETAILED_FINAL AS (
    SELECT /*+ qb_name(NEG_FINAL) */
           NHM.NEGOTIATION_NUMBER
          ,NHM.NEGOTIATION_TITLE
          ,NHM.NEGOTIATION_STATUS
          ,NHM.NEGOTIATION_OPEN_DATE
          ,NHM.NEGOTIATION_CLOSED_DATE
          ,NLM.NEGOTIATION_LINE_NUMBER
          ,NLM.NEGOTIATION_LINE_DESCRIPTION
          ,BUM.BU_NAME AS REQUISITION_BU
          ,NLM.LINE_TYPE
          ,CM.CATEGORY_NAME
          ,NLM.REQUESTED_DELIVERY_DATE
          ,NLM.CURRENT_PRICE
          ,NLM.PR_NUMBER
    FROM   NEGOTIATION_HEADER_MASTER NHM
          ,NEGOTIATION_LINE_MASTER NLM
          ,POR_REQUISITION_HEADERS_ALL PRHA
          ,CATEGORY_MASTER CM
          ,BU_MASTER BUM
          ,PARAMS P
    WHERE  NHM.AUCTION_HEADER_ID = NLM.AUCTION_HEADER_ID
      AND  NLM.PR_NUMBER = PRHA.REQUISITION_NUMBER(+)
      AND  PRHA.REQ_BU_ID = BUM.ORGANIZATION_ID(+)
      AND  NLM.CATEGORY_ID = CM.CATEGORY_ID(+)
      AND  (P.REQ_BU_NAME IS NULL OR (BUM.BU_NAME IS NOT NULL AND UPPER(BUM.BU_NAME) = UPPER(P.REQ_BU_NAME)))
)

-- Final Select
SELECT /*+ LEADING(NDF) */
       NDF.NEGOTIATION_NUMBER
      ,NDF.NEGOTIATION_TITLE
      ,NDF.NEGOTIATION_STATUS
      ,NDF.NEGOTIATION_OPEN_DATE
      ,NDF.NEGOTIATION_CLOSED_DATE
      ,NDF.NEGOTIATION_LINE_NUMBER
      ,NDF.NEGOTIATION_LINE_DESCRIPTION
      ,NDF.REQUISITION_BU
      ,NDF.LINE_TYPE
      ,NDF.CATEGORY_NAME
      ,NDF.REQUESTED_DELIVERY_DATE
      ,NDF.CURRENT_PRICE
      ,NDF.PR_NUMBER
FROM   NEGOTIATION_DETAILED_FINAL NDF
ORDER BY NDF.NEGOTIATION_NUMBER
        ,NDF.NEGOTIATION_LINE_NUMBER
