/*
TITLE: PO Detailed Report
PURPOSE: Comprehensive purchase order details with supplier, buyer, requisition, and line-level information
AUTHOR: AI Agent
PARAMETERS: P_BU_NAME, P_SUPPLIER_NAME, P_BUYER_NAME, P_PO_NUMBER, P_CREATION_DATE_FROM, P_CREATION_DATE_TO
*/

WITH
-- 1. Parameters CTE
PARAMS AS (
    SELECT /*+ qb_name(PARAMS) */
           :P_BU_NAME AS BU_NAME
          ,:P_SUPPLIER_NAME AS SUPPLIER_NAME
          ,:P_BUYER_NAME AS BUYER_NAME
          ,:P_PO_NUMBER AS PO_NUMBER
          ,TRUNC(:P_CREATION_DATE_FROM) AS CREATION_DATE_FROM
          ,TRUNC(:P_CREATION_DATE_TO) AS CREATION_DATE_TO
    FROM   DUAL
),

-- 2. PO Header Master
PO_HEADER_MASTER AS (
    SELECT /*+ qb_name(PO_HDR) MATERIALIZE PARALLEL(2) */
           PHA.PO_HEADER_ID
          ,PHA.SEGMENT1 AS PO_NUMBER
          ,PHA.CREATION_DATE
          ,PHA.TYPE_LOOKUP_CODE AS PO_STATUS
          ,PHA.CURRENCY_CODE
          ,PHA.PRC_BU_ID
          ,PHA.VENDOR_ID
          ,PHA.VENDOR_SITE_ID
          ,PHA.AGENT_ID
          ,PHA.TERMS_ID
    FROM   PO_HEADERS_ALL PHA
          ,PARAMS P
    WHERE  1=1
      AND  (P.BU_NAME IS NULL OR EXISTS (
              SELECT 1 FROM HR_ALL_ORGANIZATION_UNITS HAOU
              WHERE HAOU.ORGANIZATION_ID = PHA.PRC_BU_ID
                AND UPPER(HAOU.NAME) = UPPER(P.BU_NAME)
            ))
      AND  (P.PO_NUMBER IS NULL OR PHA.SEGMENT1 = P.PO_NUMBER)
      AND  (P.CREATION_DATE_FROM IS NULL OR TRUNC(PHA.CREATION_DATE) >= P.CREATION_DATE_FROM)
      AND  (P.CREATION_DATE_TO IS NULL OR TRUNC(PHA.CREATION_DATE) <= P.CREATION_DATE_TO)
),

-- 3. Supplier Master
SUPPLIER_MASTER AS (
    SELECT /*+ qb_name(SUPP_MST) MATERIALIZE */
           POS.VENDOR_ID
          ,POS.VENDOR_NAME
          ,POS.SEGMENT1 AS SUPPLIER_NUMBER
    FROM   POZ_SUPPLIERS_V POS
          ,PARAMS P
    WHERE  (P.SUPPLIER_NAME IS NULL OR UPPER(POS.VENDOR_NAME) = UPPER(P.SUPPLIER_NAME))
),

-- 4. Supplier Site Master (Address)
SUPPLIER_SITE_MASTER AS (
    SELECT /*+ qb_name(SUPP_SITE) MATERIALIZE */
           PSS.VENDOR_ID
          ,PSS.VENDOR_SITE_ID
          ,PSS.PRC_BU_ID
          ,TRIM(
              RTRIM(
                NVL(PSS.ADDRESS_LINE1 || CHR(10), '') ||
                NVL(PSS.ADDRESS_LINE2 || CHR(10), '') ||
                NVL(PSS.ADDRESS_LINE3 || CHR(10), '') ||
                NVL(PSS.CITY || ', ', '') ||
                NVL(PSS.STATE || ', ', '') ||
                NVL(PSS.COUNTRY, '')
              , CHR(10))
          ) AS SUPPLIER_ADDRESS
    FROM   POZ_SUPPLIER_SITES_V PSS
),

-- 5. Supplier Contact Master
SUPPLIER_CONTACT_MASTER AS (
    SELECT /*+ qb_name(SUPP_CONT) MATERIALIZE */
           VENDOR_ID
          ,VENDOR_SITE_ID
          ,CONTACT_NAME
          ,SUPPLIER_EMAIL
    FROM   (
        SELECT PSC.VENDOR_ID
              ,PSC.VENDOR_SITE_ID
              ,PSC.FULL_NAME AS CONTACT_NAME
              ,PSC.EMAIL_ADDRESS AS SUPPLIER_EMAIL
              ,ROW_NUMBER() OVER (PARTITION BY PSC.VENDOR_ID, PSC.VENDOR_SITE_ID ORDER BY PSC.VENDOR_ID, PSC.VENDOR_SITE_ID) AS RN
        FROM   POZ_SUPPLIER_CONTACTS_V PSC
        WHERE  NVL(PSC.INACTIVE_DATE, SYSDATE + 1) > SYSDATE
    )
    WHERE  RN = 1
),

-- 6. Payment Terms Master
PAYMENT_TERMS_MASTER AS (
    SELECT /*+ qb_name(PAY_TERMS) MATERIALIZE */
           AT.TERM_ID
          ,AT.NAME AS PAYMENT_TERM
    FROM   AP_TERMS AT
),

-- 7. Business Unit Master
BU_MASTER AS (
    SELECT /*+ qb_name(BU_MST) MATERIALIZE */
           HAOU.ORGANIZATION_ID
          ,HAOU.NAME AS BU_NAME
    FROM   HR_ALL_ORGANIZATION_UNITS HAOU
),

-- 8. Buyer Master (Date-Effective)
BUYER_MASTER AS (
    SELECT /*+ qb_name(BUYER_MST) MATERIALIZE */
           PAPF.PERSON_ID
          ,PNAME.FULL_NAME AS BUYER_NAME
    FROM   PER_ALL_PEOPLE_F PAPF
          ,PER_PERSON_NAMES_F PNAME
          ,PARAMS P
    WHERE  TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
      AND  TRUNC(SYSDATE) BETWEEN PNAME.EFFECTIVE_START_DATE AND PNAME.EFFECTIVE_END_DATE
      AND  PNAME.NAME_TYPE = 'GLOBAL'
      AND  PAPF.PERSON_ID = PNAME.PERSON_ID
      AND  (P.BUYER_NAME IS NULL OR UPPER(PNAME.FULL_NAME) = UPPER(P.BUYER_NAME))
),

-- 9. Buyer Email Master
BUYER_EMAIL_MASTER AS (
    SELECT /*+ qb_name(BUYER_EMAIL) MATERIALIZE */
           PERSON_ID
          ,BUYER_EMAIL
    FROM   (
        SELECT PEMAIL.PERSON_ID
              ,PEMAIL.EMAIL_ADDRESS AS BUYER_EMAIL
              ,ROW_NUMBER() OVER (PARTITION BY PEMAIL.PERSON_ID ORDER BY 
                  CASE WHEN PEMAIL.EMAIL_TYPE = 'W1' THEN 1 ELSE 2 END, PEMAIL.EMAIL_ADDRESS_ID) AS RN
        FROM   PER_EMAIL_ADDRESSES PEMAIL
    )
    WHERE  RN = 1
),

-- 10. PO Line Master
PO_LINE_MASTER AS (
    SELECT /*+ qb_name(PO_LINE) MATERIALIZE */
           PLA.PO_HEADER_ID
          ,PLA.PO_LINE_ID
          ,PLA.LINE_NUM
          ,PLA.UNIT_PRICE
          ,PLA.ITEM_DESCRIPTION
          ,PLA.UOM_CODE
    FROM   PO_LINES_ALL PLA
),

-- 10A. PO Distribution Master (for PR link)
PO_DISTRIBUTION_MASTER AS (
    SELECT /*+ qb_name(PO_DIST) MATERIALIZE */
           PDA.PO_HEADER_ID
          ,PDA.PO_LINE_ID
          ,PDA.LINE_LOCATION_ID
          ,PDA.REQ_HEADER_ID
          ,ROW_NUMBER() OVER (PARTITION BY PDA.PO_HEADER_ID, PDA.PO_LINE_ID, PDA.LINE_LOCATION_ID ORDER BY PDA.REQ_HEADER_ID) AS RN
    FROM   PO_DISTRIBUTIONS_ALL PDA
    WHERE  PDA.REQ_HEADER_ID IS NOT NULL
),

-- 11. PO Line Location Master (Shipments)
PO_LINE_LOCATION_MASTER AS (
    SELECT /*+ qb_name(PO_LINE_LOC) MATERIALIZE */
           PLLA.PO_HEADER_ID
          ,PLLA.PO_LINE_ID
          ,PLLA.LINE_LOCATION_ID
          ,PLLA.QUANTITY
          ,NVL(PLLA.AMOUNT, PLA.UNIT_PRICE * PLLA.QUANTITY) AS LINE_AMOUNT
          ,NVL(PLLA.TAX_RECOVERABLE, 0) AS TAX_RECOVERABLE
          ,PLLA.NEED_BY_DATE
    FROM   PO_LINE_LOCATIONS_ALL PLLA
          ,PO_LINE_MASTER PLA
    WHERE  PLLA.PO_LINE_ID = PLA.PO_LINE_ID
      AND  PLLA.PO_HEADER_ID = PLA.PO_HEADER_ID
      AND  NVL(PLLA.CANCEL_FLAG, 'N') = 'N'
),

-- 12. PR Master
PR_MASTER AS (
    SELECT /*+ qb_name(PR_MST) MATERIALIZE */
           PRHA.REQUISITION_HEADER_ID
          ,PRHA.SEGMENT1 AS PR_NUMBER
          ,PRHA.REQUESTER_ID
    FROM   POR_REQUISITION_HEADERS_ALL PRHA
),

-- 13. PR Requester Master (Date-Effective)
PR_REQUESTER_MASTER AS (
    SELECT /*+ qb_name(PR_REQ) MATERIALIZE */
           PAPF.PERSON_ID
          ,PNAME.FULL_NAME AS PR_REQUESTER_NAME
    FROM   PER_ALL_PEOPLE_F PAPF
          ,PER_PERSON_NAMES_F PNAME
    WHERE  TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
      AND  TRUNC(SYSDATE) BETWEEN PNAME.EFFECTIVE_START_DATE AND PNAME.EFFECTIVE_END_DATE
      AND  PNAME.NAME_TYPE = 'GLOBAL'
      AND  PAPF.PERSON_ID = PNAME.PERSON_ID
),

-- 14. Final Detailed Report
PO_DETAILED_FINAL AS (
    SELECT /*+ qb_name(PO_FINAL) */
           PHM.PO_NUMBER
          ,PHM.CREATION_DATE AS PO_CREATION_DATE
          ,PHM.PO_STATUS
          ,PHM.CURRENCY_CODE AS PO_CURRENCY_CODE
          ,PLM.LINE_NUM AS PO_LINE_NUMBER
          ,PLM.UNIT_PRICE AS PO_UNIT_PRICE
          ,PLLM.QUANTITY AS PO_QUANTITY
          ,PLLM.LINE_AMOUNT AS PO_LINE_AMOUNT
          ,PLLM.TAX_RECOVERABLE AS PO_RECOVERABLE_TAX_AMOUNT
          ,PLLM.NEED_BY_DATE
          ,PLM.ITEM_DESCRIPTION
          ,PTM.PAYMENT_TERM
          ,PLM.UOM_CODE AS UNIT_OF_MEASUREMENT
          ,SM.VENDOR_NAME AS SUPPLIER_NAME
          ,SM.SUPPLIER_NUMBER
          ,SSM.SUPPLIER_ADDRESS
          ,SSCM.CONTACT_NAME AS SUPPLIER_CONTACT_NAME
          ,SSCM.SUPPLIER_EMAIL AS SUPPLIER_EMAIL_ADDRESS
          ,BUM.BU_NAME AS PROCUREMENT_BU
          ,BM.BUYER_NAME
          ,BEM.BUYER_EMAIL
          ,PRM.PR_NUMBER
          ,PRRM.PR_REQUESTER_NAME
    FROM   PO_HEADER_MASTER PHM
          ,SUPPLIER_MASTER SM
          ,SUPPLIER_SITE_MASTER SSM
          ,SUPPLIER_CONTACT_MASTER SSCM
          ,PAYMENT_TERMS_MASTER PTM
          ,BU_MASTER BUM
          ,BUYER_MASTER BM
          ,BUYER_EMAIL_MASTER BEM
          ,PO_LINE_MASTER PLM
          ,PO_LINE_LOCATION_MASTER PLLM
          ,PO_DISTRIBUTION_MASTER PDM
          ,PR_MASTER PRM
          ,PR_REQUESTER_MASTER PRRM
    WHERE  PHM.VENDOR_ID = SM.VENDOR_ID
      AND  PHM.VENDOR_ID = SSM.VENDOR_ID(+)
      AND  PHM.VENDOR_SITE_ID = SSM.VENDOR_SITE_ID(+)
      AND  PHM.PRC_BU_ID = SSM.PRC_BU_ID(+)
      AND  PHM.VENDOR_ID = SSCM.VENDOR_ID(+)
      AND  PHM.VENDOR_SITE_ID = SSCM.VENDOR_SITE_ID(+)
      AND  PHM.TERMS_ID = PTM.TERM_ID(+)
      AND  PHM.PRC_BU_ID = BUM.ORGANIZATION_ID(+)
      AND  PHM.AGENT_ID = BM.PERSON_ID(+)
      AND  PHM.AGENT_ID = BEM.PERSON_ID(+)
      AND  PHM.PO_HEADER_ID = PLM.PO_HEADER_ID
      AND  PLM.PO_LINE_ID = PLLM.PO_LINE_ID
      AND  PHM.PO_HEADER_ID = PLLM.PO_HEADER_ID
      AND  PLLM.PO_HEADER_ID = PDM.PO_HEADER_ID(+)
      AND  PLLM.PO_LINE_ID = PDM.PO_LINE_ID(+)
      AND  PLLM.LINE_LOCATION_ID = PDM.LINE_LOCATION_ID(+)
      AND  PDM.RN(+) = 1
      AND  PDM.REQ_HEADER_ID = PRM.REQUISITION_HEADER_ID(+)
      AND  PRM.REQUESTER_ID = PRRM.PERSON_ID(+)
)

-- Final Select
SELECT /*+ LEADING(PDF) */
       PDF.PO_NUMBER
      ,PDF.PO_CREATION_DATE
      ,PDF.PO_STATUS
      ,PDF.PO_CURRENCY_CODE
      ,PDF.PO_LINE_NUMBER
      ,PDF.PO_UNIT_PRICE
      ,PDF.PO_QUANTITY
      ,PDF.PO_LINE_AMOUNT
      ,PDF.PO_RECOVERABLE_TAX_AMOUNT
      ,PDF.NEED_BY_DATE
      ,PDF.ITEM_DESCRIPTION
      ,PDF.PAYMENT_TERM
      ,PDF.UNIT_OF_MEASUREMENT
      ,PDF.SUPPLIER_NAME
      ,PDF.SUPPLIER_NUMBER
      ,PDF.SUPPLIER_ADDRESS
      ,PDF.SUPPLIER_CONTACT_NAME
      ,PDF.SUPPLIER_EMAIL_ADDRESS
      ,PDF.PROCUREMENT_BU
      ,PDF.BUYER_NAME
      ,PDF.BUYER_EMAIL
      ,PDF.PR_NUMBER
      ,PDF.PR_REQUESTER_NAME
FROM   PO_DETAILED_FINAL PDF
ORDER BY PDF.PO_NUMBER
        ,PDF.PO_LINE_NUMBER

