/*
TITLE: PR Detail Report
PURPOSE: Detailed listing of Purchase Requisitions with linked Purchase Orders, Requester information, Charge Accounts, and Supplier details
AUTHOR: AI Agent
DATE: 19-01-2026
PARAMETERS: P_PR_FROM_DATE, P_PR_TO_DATE, P_REQUESTER_NAME
*/

WITH
-- 1. Parameters CTE
PARAMS AS (
    SELECT /*+ qb_name(PARAMS) */
           TRUNC(TO_DATE(:P_PR_FROM_DATE, 'YYYY-MM-DD')) AS PR_FROM_DATE
          ,TRUNC(TO_DATE(:P_PR_TO_DATE, 'YYYY-MM-DD')) AS PR_TO_DATE
          ,:P_REQUESTER_NAME AS REQUESTER_NAME_PARAM
    FROM   DUAL
),

-- 2. PR Master (Headers filtered by creation date)
PR_MASTER AS (
    SELECT /*+ qb_name(PR_MST) MATERIALIZE PARALLEL(2) */
           PRHA.REQUISITION_HEADER_ID
          ,PRHA.REQUISITION_NUMBER
          ,PRHA.DESCRIPTION AS PR_HEADER_DESCRIPTION
          ,PRHA.CREATION_DATE AS PR_CREATION_DATE
          ,PRHA.DOCUMENT_STATUS AS PR_STATUS_CODE
          ,PRHA.REQ_BU_ID
    FROM   POR_REQUISITION_HEADERS_ALL PRHA
          ,PARAMS P
    WHERE  TRUNC(PRHA.CREATION_DATE) BETWEEN P.PR_FROM_DATE AND P.PR_TO_DATE
),

-- 3. PR Lines with Amount Calculation
PR_LINES AS (
    SELECT /*+ qb_name(PR_LN) MATERIALIZE PARALLEL(2) */
           PRLA.REQUISITION_HEADER_ID
          ,PRLA.REQUISITION_LINE_ID
          ,PRLA.REQUESTER_ID
          ,PRLA.PO_HEADER_ID
          ,ROUND(NVL(PRLA.ASSESSABLE_VALUE, 
                CASE 
                    WHEN PRLA.CURRENCY_UNIT_PRICE IS NOT NULL AND PRLA.QUANTITY IS NOT NULL 
                    THEN (PRLA.CURRENCY_UNIT_PRICE * PRLA.QUANTITY * NVL(PRLA.RATE, 1))
                    ELSE NVL(PRLA.CURRENCY_AMOUNT, 0) * NVL(PRLA.RATE, 1)
                END), 2) AS REQUISITION_AMOUNT
    FROM   POR_REQUISITION_LINES_ALL PRLA
),

-- 4. PR Distributions (Charge Account)
PR_DISTRIBUTIONS AS (
    SELECT /*+ qb_name(PR_DIST) MATERIALIZE */
           PRDA.REQUISITION_LINE_ID
          ,PRDA.DISTRIBUTION_NUMBER
          ,PRDA.CODE_COMBINATION_ID
          ,PRDA.REQ_BU_ID
    FROM   POR_REQ_DISTRIBUTIONS_ALL PRDA
),

-- 5. Requester Master (Date-Effective)
REQUESTER_MASTER AS (
    SELECT /*+ qb_name(REQ_MST) MATERIALIZE */
           PPNF.PERSON_ID
          ,PPNF.FIRST_NAME || ' ' || PPNF.LAST_NAME AS REQUESTER_NAME
    FROM   PER_PERSON_NAMES_F PPNF
    WHERE  PPNF.NAME_TYPE = 'GLOBAL'
      AND  TRUNC(SYSDATE) BETWEEN TRUNC(PPNF.EFFECTIVE_START_DATE) 
                              AND TRUNC(PPNF.EFFECTIVE_END_DATE)
),

-- 6. PR Status Lookup
PR_STATUS_LOOKUP AS (
    SELECT /*+ qb_name(PR_STAT) MATERIALIZE */
           FLVT.LOOKUP_CODE
          ,FLVT.MEANING AS PR_STATUS
    FROM   FND_LOOKUP_VALUES_TL FLVT
    WHERE  FLVT.LOOKUP_TYPE = 'POR_DOCUMENT_STATUS'
      AND  FLVT.VIEW_APPLICATION_ID = 0
      AND  FLVT.SET_ID = 0
      AND  FLVT.LANGUAGE = USERENV('LANG')
),

-- 7. PO Master (for PO Number)
PO_MASTER AS (
    SELECT /*+ qb_name(PO_MST) MATERIALIZE */
           PHA.PO_HEADER_ID
          ,PHA.SEGMENT1 AS PO_NUMBER
          ,PHA.VENDOR_ID
    FROM   PO_HEADERS_ALL PHA
),

-- 8. Supplier Master
SUPPLIER_MASTER AS (
    SELECT /*+ qb_name(SUPP_MST) MATERIALIZE */
           PSV.VENDOR_ID
          ,PSV.VENDOR_NAME AS SUPPLIER_NAME
    FROM   POZ_SUPPLIERS_V PSV
),

-- 9. Charge Account (GL Code Combinations)
CHARGE_ACCOUNT AS (
    SELECT /*+ qb_name(CHARGE_ACC) MATERIALIZE */
           GCC.CODE_COMBINATION_ID
          ,GCC.CONCATENATED_SEGMENTS AS CHARGE_ACCOUNT
    FROM   GL_CODE_COMBINATIONS GCC
),

-- 10. PR Detail (Final Join)
PR_DETAIL AS (
    SELECT /*+ qb_name(PR_DTL) MATERIALIZE */
           PRM.REQUISITION_NUMBER
          ,NVL(RM.REQUESTER_NAME, 'Unknown') AS REQUESTER_NAME
          ,PRM.PR_HEADER_DESCRIPTION
          ,TO_CHAR(PRM.PR_CREATION_DATE, 'DD-MON-YYYY') AS REQUISITION_CREATION_DATE
          ,NVL(PSL.PR_STATUS, PRM.PR_STATUS_CODE) AS REQUISITION_STATUS
          ,PRL.REQUISITION_AMOUNT
          ,POM.PO_NUMBER AS PURCHASE_ORDER_NUMBER
          ,NVL(CA.CHARGE_ACCOUNT, 'Not Assigned') AS CHARGE_ACCOUNT
          ,NVL(SM.SUPPLIER_NAME, 'Not Converted to PO') AS SUPPLIER_NAME
    FROM   PR_MASTER PRM
          ,PR_LINES PRL
          ,PR_DISTRIBUTIONS PRD
          ,REQUESTER_MASTER RM
          ,PR_STATUS_LOOKUP PSL
          ,PO_MASTER POM
          ,SUPPLIER_MASTER SM
          ,CHARGE_ACCOUNT CA
          ,PARAMS P
    WHERE  PRM.REQUISITION_HEADER_ID = PRL.REQUISITION_HEADER_ID
      AND  PRL.REQUISITION_LINE_ID = PRD.REQUISITION_LINE_ID
      AND  PRL.REQUESTER_ID = RM.PERSON_ID(+)
      AND  PRM.PR_STATUS_CODE = PSL.LOOKUP_CODE(+)
      AND  PRL.PO_HEADER_ID = POM.PO_HEADER_ID(+)
      AND  POM.VENDOR_ID = SM.VENDOR_ID(+)
      AND  PRD.CODE_COMBINATION_ID = CA.CODE_COMBINATION_ID(+)
      AND  PRM.REQ_BU_ID = PRD.REQ_BU_ID
      -- Requester Name Filter with NVL (optional parameter)
      AND  NVL(P.REQUESTER_NAME_PARAM, RM.REQUESTER_NAME) = RM.REQUESTER_NAME
)

-- Final Select
SELECT /*+ LEADING(PRD) */
       PRD.REQUISITION_NUMBER
      ,PRD.REQUESTER_NAME
      ,PRD.PR_HEADER_DESCRIPTION AS REQUISITION_HEADER_DESCRIPTION
      ,PRD.REQUISITION_CREATION_DATE
      ,PRD.REQUISITION_STATUS
      ,PRD.REQUISITION_AMOUNT
      ,PRD.PURCHASE_ORDER_NUMBER
      ,PRD.CHARGE_ACCOUNT
      ,PRD.SUPPLIER_NAME
FROM   PR_DETAIL PRD
ORDER BY PRD.REQUISITION_NUMBER
        ,PRD.REQUISITION_CREATION_DATE DESC
        ,PRD.CHARGE_ACCOUNT

