/*
TITLE: Supplier Master Report
PURPOSE: Comprehensive supplier details with contacts, bank accounts, tax information, and classifications
MODULES: SCM - Supplier Management
PARAMETERS:
  - :P_BUSINESS_UNIT_NAME - Business Unit Name (Optional)
  - :P_SUPPLIER_STATUS - Supplier Status (Optional: 'Active' or 'Inactive')
  - :P_SUPPLIER_TYPE - Supplier Type/Vendor Type (Optional)
  - :P_SUPPLIER_CREATION_DATE_FROM - Supplier Creation Date From (Optional)
  - :P_SUPPLIER_CREATION_DATE_TO - Supplier Creation Date To (Optional)
AUTHOR: AI Agent
DATE: 19-01-2026
*/

WITH
-- 1. Parameters CTE
PARAMS AS (
    SELECT /*+ qb_name(PARAMS) */
           TRUNC(:P_SUPPLIER_CREATION_DATE_FROM) P_CREATION_DATE_FROM
          ,TRUNC(:P_SUPPLIER_CREATION_DATE_TO) P_CREATION_DATE_TO
          ,:P_BUSINESS_UNIT_NAME P_BUSINESS_UNIT_NAME
          ,:P_SUPPLIER_STATUS P_SUPPLIER_STATUS
          ,:P_SUPPLIER_TYPE P_SUPPLIER_TYPE
    FROM   DUAL
),

-- 2. Supplier Master (filtered by creation date)
SUPPLIER_MASTER AS (
    SELECT /*+ qb_name(SUPP_MST) MATERIALIZE PARALLEL(2) */
           PSV.VENDOR_ID
          ,PSV.SEGMENT1 AS SUPPLIER_NUMBER
          ,PSV.VENDOR_NAME AS SUPPLIER_NAME
          ,PSV.VENDOR_TYPE_LOOKUP_CODE AS VENDOR_TYPE_CODE
          ,PSV.VENDOR_TYPE_LOOKUP_CODE AS SUPPLIER_CATEGORY
          ,PSV.CREATION_DATE AS SUPPLIER_CREATION_DATE
          ,PSV.PARTY_ID
    FROM   POZ_SUPPLIERS_V PSV
          ,PARAMS P
    WHERE  (P.P_CREATION_DATE_FROM IS NULL OR TRUNC(PSV.CREATION_DATE) >= P.P_CREATION_DATE_FROM)
      AND  (P.P_CREATION_DATE_TO IS NULL OR TRUNC(PSV.CREATION_DATE) <= P.P_CREATION_DATE_TO)
),

-- 3. Supplier Sites
SUPPLIER_SITES AS (
    SELECT /*+ qb_name(SUPP_SITES) MATERIALIZE */
           PSSV.VENDOR_ID
          ,PSSV.VENDOR_SITE_ID
          ,PSSV.PARTY_SITE_NAME AS SITE_NAME
          ,PSSV.PARTY_SITE_ID
          ,PSSV.TERMS_ID
          ,PSSV.PRC_BU_ID
    FROM   POZ_SUPPLIER_SITES_V PSSV
),

-- 4. Supplier Address
SUPPLIER_ADDRESS AS (
    SELECT /*+ qb_name(SUPP_ADDR) MATERIALIZE */
           PSAV.VENDOR_ID
          ,PSAV.PARTY_SITE_ID
          ,PSAV.ADDRESS1 AS ADDRESS_LINE1
          ,PSAV.ADDRESS2 AS ADDRESS_LINE2
          ,PSAV.CITY
          ,PSAV.PHONE_NUMBER
    FROM   POZ_SUPPLIER_ADDRESS_V PSAV
),

-- 5. Vendor Type Lookup
VENDOR_TYPE_LOOKUP AS (
    SELECT /*+ qb_name(VEND_TYPE) MATERIALIZE */
           FLVT.LOOKUP_CODE
          ,FLVT.MEANING AS VENDOR_TYPE
    FROM   FND_LOOKUP_VALUES_TL FLVT
    WHERE  FLVT.LOOKUP_TYPE = 'ORA_POZ_VENDOR_TYPE'
      AND  FLVT.VIEW_APPLICATION_ID = 0
      AND  FLVT.SET_ID = 0
      AND  FLVT.LANGUAGE = USERENV('LANG')
),

-- 6. Vendor Status Lookup
VENDOR_STATUS_LOOKUP AS (
    SELECT /*+ qb_name(VEND_STAT) MATERIALIZE */
           HP.PARTY_ID
          ,HP.STATUS AS STATUS_CODE
          ,DECODE(HP.STATUS, 'A', 'Active', 'I', 'Inactive', 'Inactive') AS VENDOR_STATUS
    FROM   HZ_PARTIES HP
),

-- 7. Tax Profile
TAX_PROFILE AS (
    SELECT /*+ qb_name(TAX_PROF) MATERIALIZE */
           ZPTP.PARTY_ID
          ,ZPTP.REP_REGISTRATION_NUMBER AS TAX_REGISTRATION_NUMBER
          ,ZPTP.TAX_CLASSIFICATION_CODE
    FROM   ZX_PARTY_TAX_PROFILE ZPTP
),

-- 8. Business Classifications (for Trade License only)
BUSINESS_CLASSIFICATIONS AS (
    SELECT /*+ qb_name(BUS_CLASS) MATERIALIZE */
           PBCV.VENDOR_ID
          ,MAX(CASE 
                  WHEN UPPER(PBCV.DISPLAYED_FIELD) LIKE '%TRADE%LICENSE%' 
                     OR UPPER(PBCV.DISPLAYED_FIELD) LIKE '%LICENSE%'
                     OR UPPER(PBCV.CERTIFYING_AGENCY) LIKE '%TRADE%LICENSE%'
                     OR UPPER(PBCV.CERTIFYING_AGENCY) LIKE '%LICENSE%'
                  THEN PBCV.CERTIFICATE_NUMBER
                  ELSE NULL
              END) AS TRADE_LICENSE_NUMBER
    FROM   POZ_BUSINESS_CLASSIFICATIONS_V PBCV
    WHERE  PBCV.STATUS = 'A'
    GROUP BY PBCV.VENDOR_ID
),

-- 9. Bank Master (Primary Bank Account Only)
BANK_MASTER AS (
    SELECT /*+ qb_name(BANK_MST) MATERIALIZE */
           IAO.ACCOUNT_OWNER_PARTY_ID
          ,IEBA.BANK_ACCOUNT_NUM AS BANK_ACCOUNT_NUMBER
          ,IEBA.BANK_ACCOUNT_NAME
          ,CE.BANK_NAME
          ,CE.BANK_NUMBER
          ,IEPA.SUPPLIER_SITE_ID
    FROM   IBY_EXT_BANK_ACCOUNTS IEBA
          ,IBY_ACCOUNT_OWNERS IAO
          ,IBY_EXTERNAL_PAYEES_ALL IEPA
          ,IBY_PMT_INSTR_USES_ALL IPIUA
          ,CE_BANKS_V CE
    WHERE  IEBA.EXT_BANK_ACCOUNT_ID = IAO.EXT_BANK_ACCOUNT_ID
      AND  IAO.PRIMARY_FLAG = 'Y'
      AND  IAO.ACCOUNT_OWNER_PARTY_ID = IEPA.PAYEE_PARTY_ID
      AND  IAO.EXT_BANK_ACCOUNT_ID = IPIUA.INSTRUMENT_ID
      AND  IEPA.EXT_PAYEE_ID = IPIUA.EXT_PMT_PARTY_ID
      AND  IEBA.BANK_ID = CE.BANK_PARTY_ID(+)
),

-- 10. Business Unit Master
BUSINESS_UNIT_MASTER AS (
    SELECT /*+ qb_name(BU_MST) MATERIALIZE */
           FABUV.BU_ID
          ,FABUV.BU_NAME
    FROM   FUN_ALL_BUSINESS_UNITS_V FABUV
),

-- 11. Payment Terms Master
PAYMENT_TERMS_MASTER AS (
    SELECT /*+ qb_name(PAY_TERMS) MATERIALIZE */
           APT.TERM_ID
          ,APT.NAME AS PAYMENT_TERM
    FROM   AP_TERMS_TL APT
    WHERE  APT.LANGUAGE = USERENV('LANG')
)

-- 12. Final SELECT
SELECT /*+ LEADING(SM SS) USE_HASH(SS SA) */
       SM.SUPPLIER_NAME AS "Supplier Name"
      ,SM.SUPPLIER_NUMBER AS "Supplier Number"
      ,NVL(VTL.VENDOR_TYPE, SM.VENDOR_TYPE_CODE) AS "Vendor Type"
      ,NVL(VTL.VENDOR_TYPE, SM.SUPPLIER_CATEGORY) AS "Supplier Category"
      ,TO_CHAR(SM.SUPPLIER_CREATION_DATE, 'DD-MON-YYYY') AS "Supplier Creation Date"
      ,NVL(SS.SITE_NAME, 'N/A') AS "Supplier Site Name"
      ,NVL(SS.SITE_NAME, 'N/A') AS "Address Name"
      ,NVL(SA.ADDRESS_LINE1, 'N/A') AS "Address Line 1"
      ,NVL(SA.ADDRESS_LINE2, 'N/A') AS "Address Line 2"
      ,NVL(SA.CITY, 'N/A') AS "City"
      ,NVL(SA.PHONE_NUMBER, 'N/A') AS "Phone Number"
      ,NVL(VSL.VENDOR_STATUS, 'Inactive') AS "Vendor Status"
      ,NVL(BM.BANK_ACCOUNT_NUMBER, 'N/A') AS "Bank Account Number"
      ,NVL(BM.BANK_ACCOUNT_NAME, 'N/A') AS "Bank Account Name"
      ,NVL(BM.BANK_NAME, 'N/A') AS "Bank Name"
      ,NVL(BM.BANK_NUMBER, 'N/A') AS "Bank Number"
      ,NVL(BUM.BU_NAME, 'N/A') AS "Business Unit Name"
      ,NVL(TP.TAX_REGISTRATION_NUMBER, 'N/A') AS "Tax Registration Number"
      ,NVL(TP.TAX_CLASSIFICATION_CODE, 'N/A') AS "Tax Classification"
      ,NVL(PTM.PAYMENT_TERM, 'N/A') AS "Payment Term"
      ,NVL(BC.TRADE_LICENSE_NUMBER, 'N/A') AS "Trade License Number"
FROM   SUPPLIER_MASTER SM
      ,SUPPLIER_SITES SS
      ,SUPPLIER_ADDRESS SA
      ,VENDOR_TYPE_LOOKUP VTL
      ,VENDOR_STATUS_LOOKUP VSL
      ,TAX_PROFILE TP
      ,BUSINESS_CLASSIFICATIONS BC
      ,BANK_MASTER BM
      ,BUSINESS_UNIT_MASTER BUM
      ,PAYMENT_TERMS_MASTER PTM
      ,PARAMS P
WHERE  SM.VENDOR_ID = SS.VENDOR_ID(+)
  AND  SS.PARTY_SITE_ID = SA.PARTY_SITE_ID(+)
  AND  SM.VENDOR_TYPE_CODE = VTL.LOOKUP_CODE(+)
  AND  SM.PARTY_ID = VSL.PARTY_ID(+)
  AND  SM.PARTY_ID = TP.PARTY_ID(+)
  AND  SM.VENDOR_ID = BC.VENDOR_ID(+)
  AND  SM.PARTY_ID = BM.ACCOUNT_OWNER_PARTY_ID(+)
  AND  SS.VENDOR_SITE_ID = BM.SUPPLIER_SITE_ID(+)
  AND  SS.PRC_BU_ID = BUM.BU_ID(+)
  AND  SS.TERMS_ID = PTM.TERM_ID(+)
  AND  (P.P_BUSINESS_UNIT_NAME IS NULL OR BUM.BU_NAME = P.P_BUSINESS_UNIT_NAME)
  AND  NVL(P.P_SUPPLIER_STATUS, NVL(VSL.VENDOR_STATUS, 'Inactive')) = NVL(VSL.VENDOR_STATUS, 'Inactive')
  AND  NVL(P.P_SUPPLIER_TYPE, NVL(VTL.VENDOR_TYPE, SM.VENDOR_TYPE_CODE)) = NVL(VTL.VENDOR_TYPE, SM.VENDOR_TYPE_CODE)
ORDER BY SM.SUPPLIER_NUMBER
        ,SM.SUPPLIER_NAME
        ,SS.SITE_NAME
        ,BUM.BU_NAME

